[package]
name = "whois2"
version = "0.1.0"
authors = ["Timofey Kulin"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
idna = "0.2.0"
